<html>
    <body>
        <div id="mainContent">
            <form name="register" id="register" method="post" action="http://localhost/development/public/index.php/user/register">
                <div>
                    <label>First name</label>
                    <input type="text" name="fName" id="fName"  placeholder="First Name" value="first name" />
                </div>
                <div>
                    <label>Last name</label>
                    <input type="text" name="lName" id="lName" placeholder="Last Name" value="l namne" />

                </div>
                <div>
                    <label>Email</label>
                    <input type="text" name="email" id="email"  placeholder="Email" value="exyz@gmail.com"/>

                </div>
                <div>
                    <label>UserName</label>
                    <input type="text" name="userName" id="userName" required="true" placeholder="Login User Name" value="aaa" />

                </div>
                <div>
                    <label>Password</label>
                    <input type="password" name="password" id="password" required="true" placeholder="Password" value="password"/>
                </div>
                <div>
                    <label>Gender</label>
                    <select id="gender" name="gender">
                        <option value="">Select</option>
                        <option value="Male" selected>Male</option>
                        <option value="Female">Female</option>
                    </select>
                </div>
                <input type="submit" name="btnsubmit" id="btnsubmit"/>
            </form>
        </div>
    </body>
</html>