<?php
echo $this->doctype();
?>
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <?php echo $this->headTitle() ?>
        <script type="text/javascript" src="js/lib/jquery-1.11.1.min.js"></script>
    </head>
    <body>
        <div id="wrapper">
            <header>
                <nav>

                </nav>
            </header>
            <div id="mastercontainer">
                <?php echo $this->layout()->content; ?>
            </div>
        </div><!--#wrapper-->
        <footer></footer>
    </body>
</html>
