<?php
echo $this->doctype();
?>
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <?php echo $this->headTitle() ?>
        <link rel="stylesheet" type="text/css" media="screen" href="<?php echo $this->baseUrl(); ?>/css/common.css" />
        <script src="<?php echo $this->baseUrl(); ?>/js/common.js" type="text/javascript"></script>
    </head>
    <body>
        <div id="wrapper">
            <header>
                <nav>
                    <a href="<?php echo $this->baseUrl(); ?>/index.php/dashboard/logout">Logout</a>
                </nav>
            </header>
            <div id="mastercontainer">
                <?php echo $this->layout()->content; ?>
            </div>
        </div><!--#wrapper-->
        <div id="alerts" class="alert-top hidden">
            <div class="alert-wrapper">
                <div class="alert alert-success alert-block hidden">
                    <strong></strong>
                    <span></span>
                    <a class="message-close">x</a>
                </div>
                <div class="alert alert-danger alert-block hidden">
                    <div class="messageDiv">
                        <strong></strong>
                        <span></span></div>
                    <a class="message-close">x</a>
                </div>
            </div>
        </div>
        <footer></footer>
    </body>
</html>
